### ISSUE TITLE
Add a screenshot

### ISSUE THREAD

**Issue by anoadragon453** [koma-im/kotlin-matrix-userbots#1]
Sounds cool, but what does it look like :D

**Comment by yuforia** [comment]
@anoadragon453 there is one in the [repo of the desktop client](https://github.com/koma-im/continuum-desktop)

here is the screenshot
![continuum](https://camo.githubusercontent.com/1520c6f63200c996356508ecb305fd2b4e4ce997/68747470733a2f2f636f6e74696e75756d2e6c696e6b2f73637265656e73686f74732f7072696d6172792d707265766965772e706e67)

**Comment by anoadragon453** [comment]
I think I came to this repo thinking it was a client, when it's clearly a bot framework. Probably doesn't need any pictures in that case.
